### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by HelgaListopad** [AlexeyParfimovich/webix-practice#3]
The overall structure is well-planned, however, there is a couple of issues to improve. 
If you have any questions related to the code, I'll be glad to answer them here.

1. The height of the main part of the app (`section`) seems to be static and the footer takes the rest of the available space.
To avoid that, you may need to check if any component has a fixed height that could shrink the layout.
In case the layout is adjusted only to the form (all inputs have a static height by default), you can add a [spacer](https://slides.com/ihelga/webixlayouts#/18) after other form elements.
If the footer (template) is still bigger than expected, the static height (or `autoheight`) will help to adjust it to the picture in the task description.

2. Form values. 
It's great to have interaction between form and the datatable in addition to the main task, but unfortunately, values will never pass current validation rules. 
The picture in the task does not necessarily imply a datepicker (a text input also counts), but I agree that the datepicker is more appropriate here. Still, its configuration is the origin of the issue. 
The datepicker returns the value as a JS Date object (default), while the validation rule is `isNumber`. 
To resolve it, you can validate the value with a different rule (as a date or `isNotEmpty`), then add a few lines of code to extract a year from the Date object before adding a new item (with the extracted year) to the datatable:
https://github.com/AlexeyParfimovich/webix-practice/blob/6b01fee6aa323aef75a9b649858f6d9e08388707/scripts/section.filmForm.js#L4

___________________
Appearance: a value in datepicker can be [displayed](https://docs.webix.com/api__link__ui.datepicker_format_config.html) in different ways, so it is possible to render a year instead of the full date:
```javascript
view:"datepicker",
type:"year",
format: "%Y"
```

**Comment by AlexeyParfimovich** [comment]
Thanks a lot for the review,
As for the datepicker, I just tried a few different input fields and missed proper testing after implementation. I checked - it is need to use all your recommendations for this request. I got it.

As for the height of the main part of the application, this is still a problem for me.
I have already experimented with different properties of the CSS and webix objects, and only found out that the height of the "section" form has a fixed size for some reason. 
It seems I need more time to investigate the issue.

**Comment by HelgaListopad** [comment]
> the height of the "section" form has a fixed size for some reason.

It is the expected behaviour. All sizes in Webix are [set and calculated](https://docs.webix.com/desktop__dimensions.html) in JS, so please note that CSS styling [cannot be used](https://docs.webix.com/desktop__styling.html#wherecsscanandcannotbeapplied) to change the size of a component.

> It seems I need more time to investigate the issue.

The spacer is currently misplaced. It does fill the rest of the space, but in the wrong part of the UI.
Here are more details on the sizing rules and a reason/solution for the problem.
<details><summary>Click to reveal</summary>
<p>
Ideally, a spacer should be placed inside a form (or below it) to restore the correct sizing of the layout.

Most of the components in Webix are designed to fill all available space by default, however, some of the small widgets (inputs and calendar) have the default `height` in their configuration.
The parent container usually adjusts to inner views, if they have constant height or width. The form is adjusted to nested controls (default height of buttons and inputs is 38px in the Material skin), then the entire `section` is adjusted to the form. 
</p></details>

**Comment by AlexeyParfimovich** [comment]
Got it!
Thanks for the valuable tip.
```
The form is adjusted to nested controls ..., then the entire section is adjusted to the form
```
The issue solved.

**Comment by HelgaListopad** [comment]
Great, thank you!
